class ProjectCategory {
  final String id;
  final String name;
  final String description;

  ProjectCategory({
    required this.id,
    required this.name,
    required this.description,
  });
}

class Project {
  final String id;
  final String title;
  final String description;
  final String category;
  final String type; // 'web', 'android', 'ios', 'all'
  final List<String> technologies;
  final String? imageUrl;

  Project({
    required this.id,
    required this.title,
    required this.description,
    required this.category,
    required this.type,
    required this.technologies,
    this.imageUrl,
  });
}

class ProjectData {
  static final List<ProjectCategory> categories = [
    ProjectCategory(
      id: 'blockchain',
      name: 'Blockchain Projects',
      description: 'Decentralized applications and smart contracts',
    ),
    ProjectCategory(
      id: 'ar_vr',
      name: 'AR & VR Projects',
      description: 'Augmented and Virtual Reality applications',
    ),
    ProjectCategory(
      id: 'data_science',
      name: 'Data Science',
      description: 'Data analysis and visualization projects',
    ),
    ProjectCategory(
      id: 'machine_learning',
      name: 'Machine Learning',
      description: 'AI and ML powered applications',
    ),
    ProjectCategory(
      id: 'web_frameworks',
      name: 'Angular/Node React JS',
      description: 'Modern web framework applications',
    ),
    ProjectCategory(
      id: 'php',
      name: 'PHP Projects',
      description: 'Server-side web applications',
    ),
    ProjectCategory(
      id: 'data_mining',
      name: 'Data Mining',
      description: 'Data extraction and pattern recognition',
    ),
    ProjectCategory(
      id: 'android',
      name: 'Android Projects',
      description: 'Native Android applications',
    ),
    ProjectCategory(
      id: 'smart_card',
      name: 'Smart Card/Biometrics',
      description: 'Security and authentication systems',
    ),
    ProjectCategory(
      id: 'dotnet',
      name: 'Dotnet Projects',
      description: 'Microsoft .NET applications',
    ),
    ProjectCategory(
      id: 'web_based',
      name: 'Web Based',
      description: 'General web applications',
    ),
    ProjectCategory(
      id: 'matlab',
      name: 'Matlab Projects',
      description: 'Mathematical and scientific computing',
    ),
    ProjectCategory(
      id: 'security',
      name: 'Information Security',
      description: 'Cybersecurity and data protection',
    ),
    ProjectCategory(
      id: 'ios',
      name: 'iOS Projects',
      description: 'Native iOS applications',
    ),
    ProjectCategory(
      id: 'ai',
      name: 'Artificial Intelligence',
      description: 'AI-powered intelligent systems',
    ),
    ProjectCategory(
      id: 'embedded',
      name: 'Embedded Projects',
      description: 'Hardware and IoT applications',
    ),
  ];

  // Web App Projects - First batch
  static final List<Project> webProjects = [
    Project(
      id: 'ambulance_booking',
      title: 'Ambulance Booking System using Python',
      description: 'Emergency medical service booking platform',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'PostgreSQL', 'Bootstrap'],
    ),
    Project(
      id: 'chatbot_assistant',
      title: 'Chatbot Assistant System using Python',
      description: 'AI-powered customer service chatbot',
      category: 'ai',
      type: 'web',
      technologies: ['Python', 'NLP', 'Flask', 'TensorFlow'],
    ),
    Project(
      id: 'child_vaccination',
      title: 'Child Vaccination Management System using Python',
      description: 'Healthcare management for child immunization',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'MySQL', 'Chart.js'],
    ),
    Project(
      id: 'complaint_registration',
      title: 'Online Complaint Registration & Management System using Python',
      description: 'Digital complaint handling and tracking system',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Flask', 'SQLite', 'Bootstrap'],
    ),
    Project(
      id: 'organ_donation',
      title: 'Organ Donation System using Python',
      description: 'Life-saving organ matching and donation platform',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'PostgreSQL', 'Redis'],
    ),
    Project(
      id: 'student_feedback',
      title: 'Student Feedback Review System using Python',
      description: 'Educational feedback collection and analysis',
      category: 'data_science',
      type: 'web',
      technologies: ['Python', 'Django', 'Pandas', 'Matplotlib'],
    ),
    Project(
      id: 'real_estate_blockchain',
      title: 'Real Estate Booking System using Smart Contracts',
      description: 'Blockchain-based property transaction system',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Ethereum', 'React'],
    ),
    Project(
      id: 'crowdfunding_blockchain',
      title: 'Trusted Crowdfunding Platform Using a Smart Contract',
      description: 'Decentralized fundraising platform',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'IPFS', 'React'],
    ),
    Project(
      id: 'loan_management_blockchain',
      title: 'Blockchain based Loan Management System with Smart Contracts',
      description: 'Decentralized lending and borrowing platform',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Truffle', 'Node.js'],
    ),
    Project(
      id: 'rental_property_blockchain',
      title: 'Blockchain Rental Property System with Smart Contracts',
      description: 'Smart contract-based property rental system',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'MetaMask', 'Vue.js'],
    ),
    Project(
      id: 'anti_money_laundering',
      title: 'Anti-Money Laundering System using Blockchain',
      description: 'Blockchain-based AML compliance and monitoring',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Python', 'Machine Learning'],
    ),
    Project(
      id: 'blockchain_transaction_settlement',
      title: 'Blockchain-based Transaction and Settlement System',
      description: 'Secure financial transaction processing platform',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Financial APIs', 'Security'],
    ),
    Project(
      id: 'blockchain_file_sharing',
      title: 'Blockchain based Cloud File Sharing System',
      description: 'Decentralized secure file storage and sharing',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'IPFS', 'Web3.js', 'Encryption'],
    ),
    Project(
      id: 'blockchain_cross_border',
      title: 'Blockchain based Cross Border Payment System',
      description: 'International payment processing with blockchain',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Payment Gateways', 'Compliance'],
    ),
    Project(
      id: 'blockchain_merchant_payment',
      title: 'Blockchain based Merchant Payment System',
      description: 'Secure merchant transaction processing',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'POS Integration', 'Mobile Payments'],
    ),
    Project(
      id: 'organization_finance_blockchain',
      title: 'Organization Finance Tracking System using Blockchain',
      description: 'Corporate financial management with transparency',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Financial Reporting', 'Audit Trail'],
    ),
    Project(
      id: 'blockchain_identity_security',
      title: 'Blockchain based Personal Identity Security System',
      description: 'Decentralized identity verification and management',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Identity Standards', 'Privacy'],
    ),
    Project(
      id: 'face_recognition_attendance',
      title: 'Face Recognition Attendance System using Python',
      description: 'AI-powered attendance tracking with facial recognition',
      category: 'ai',
      type: 'web',
      technologies: ['Python', 'OpenCV', 'TensorFlow', 'Flask'],
    ),
    Project(
      id: 'website_vulnerability_scanner',
      title: 'Website Vulnerability Scanning System',
      description: 'Automated security assessment and vulnerability detection',
      category: 'security',
      type: 'web',
      technologies: ['Python', 'Nmap', 'SQLMap', 'Django'],
    ),
    Project(
      id: 'electronics_ecommerce',
      title: 'Electronics Ecommerce Website Python',
      description: 'Full-featured online electronics marketplace',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'PostgreSQL', 'Stripe'],
    ),
    Project(
      id: 'mental_health_nlp',
      title: 'Mental Health Check app using NLP Flutter',
      description: 'AI-powered mental health assessment application',
      category: 'ai',
      type: 'web',
      technologies: ['Flutter', 'NLP', 'TensorFlow', 'Firebase'],
    ),
    Project(
      id: 'veterinary_appointment',
      title: 'Veterinary Appointment Scheduling App Flutter',
      description: 'Pet healthcare appointment management system',
      category: 'web_based',
      type: 'web',
      technologies: ['Flutter', 'Firebase', 'Calendar API', 'Push Notifications'],
    ),
    Project(
      id: 'fuel_delivery',
      title: 'Online Fuel Delivery Flutter App',
      description: 'On-demand fuel delivery service platform',
      category: 'web_based',
      type: 'web',
      technologies: ['Flutter', 'Google Maps', 'Payment Gateway', 'Real-time Tracking'],
    ),
    Project(
      id: 'weather_monitoring',
      title: 'Real Time Global Weather Monitoring App Flutter',
      description: 'Comprehensive weather tracking and forecasting',
      category: 'data_science',
      type: 'web',
      technologies: ['Flutter', 'Weather API', 'Charts', 'Real-time Data'],
    ),
    Project(
      id: 'property_registration_blockchain',
      title: 'Property Registration Management System using Blockchain',
      description: 'Secure property ownership and transfer system',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'IPFS', 'Smart Contracts'],
    ),
    Project(
      id: 'patient_data_blockchain',
      title: 'Patient Data Management System using Blockchain',
      description: 'Secure healthcare data management with blockchain',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Healthcare Standards', 'Privacy'],
    ),
    Project(
      id: 'electronic_voting_blockchain',
      title: 'Electronic Voting System using Blockchain',
      description: 'Transparent and secure digital voting platform',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Cryptography', 'Voting Protocols'],
    ),
    Project(
      id: 'loyalty_points_blockchain',
      title: 'Loyalty Points Exchange System using Blockchain',
      description: 'Cross-platform loyalty rewards management',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Token Standards', 'DeFi'],
    ),
    Project(
      id: 'ngo_management_blockchain',
      title: 'NGO Management System using Blockchain',
      description: 'Transparent charity and donation tracking system',
      category: 'blockchain',
      type: 'web',
      technologies: ['Solidity', 'Web3.js', 'Transparency', 'Donation Tracking'],
    ),
    Project(
      id: 'nursery_plant_shopping',
      title: 'Online Nursery Plant Shopping Website Python',
      description: 'E-commerce platform for plants and gardening supplies',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'E-commerce', 'Payment Gateway'],
    ),
    Project(
      id: 'pdf_text_converter',
      title: 'Online PDF to Text Converter & Language Translator Python',
      description: 'Document processing and translation service',
      category: 'ai',
      type: 'web',
      technologies: ['Python', 'OCR', 'Translation API', 'Document Processing'],
    ),
    Project(
      id: 'fake_logo_detection',
      title: 'Online Fake Logo Detection System',
      description: 'AI-powered brand protection and logo verification',
      category: 'ai',
      type: 'web',
      technologies: ['Python', 'Computer Vision', 'Machine Learning', 'Image Processing'],
    ),
    Project(
      id: 'three_level_password',
      title: 'Three Level Image Password Authentication',
      description: 'Multi-layer security system with image-based authentication',
      category: 'security',
      type: 'web',
      technologies: ['Python', 'Image Processing', 'Security', 'Authentication'],
    ),
    Project(
      id: 'student_grievance',
      title: 'Students Grievance Redressal Cell Python',
      description: 'Educational complaint management and resolution system',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'Workflow Management', 'Notifications'],
    ),
    Project(
      id: 'fashion_stylist',
      title: 'Online Fashion Stylist Website',
      description: 'AI-powered fashion recommendation and styling platform',
      category: 'ai',
      type: 'web',
      technologies: ['Python', 'Machine Learning', 'Image Recognition', 'Recommendations'],
    ),
    Project(
      id: 'cancer_prediction',
      title: 'Cancer Prediction using Naive Bayes',
      description: 'Machine learning model for early cancer detection',
      category: 'machine_learning',
      type: 'web',
      technologies: ['Python', 'Scikit-learn', 'Pandas', 'Matplotlib'],
    ),
    Project(
      id: 'behavioral_analysis',
      title: 'Behavioural Analysis using Gamification Techniques',
      description: 'User behavior analysis through gamified interactions',
      category: 'data_science',
      type: 'web',
      technologies: ['Python', 'Django', 'D3.js', 'PostgreSQL'],
    ),
    Project(
      id: 'charity_management',
      title: 'Online Charity Management System',
      description: 'Comprehensive platform for charity organizations',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'Payment Gateway', 'Reporting'],
    ),
    Project(
      id: 'voice_assistant',
      title: 'Voice based Intelligent Virtual Assistance for Windows',
      description: 'Desktop voice assistant with AI capabilities',
      category: 'ai',
      type: 'web',
      technologies: ['Python', 'Speech Recognition', 'NLP', 'Tkinter'],
    ),
    Project(
      id: 'web_chat_webcam',
      title: 'Web-based Chat Application with Webcam using PHP',
      description: 'Real-time communication platform with video support',
      category: 'php',
      type: 'web',
      technologies: ['PHP', 'WebRTC', 'Socket.io', 'MySQL'],
    ),
    Project(
      id: 'tutors_finder',
      title: 'Online Private Tutors Finder System',
      description: 'Educational marketplace connecting students and tutors',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'Payment Gateway', 'Scheduling'],
    ),
    Project(
      id: 'school_administration',
      title: 'Online School Administration Management System',
      description: 'Comprehensive school management platform',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'PostgreSQL', 'Reporting'],
    ),
    Project(
      id: 'fitness_club',
      title: 'Fitness Club Management System',
      description: 'Gym and fitness center management platform',
      category: 'web_based',
      type: 'web',
      technologies: ['Python', 'Django', 'Membership Management', 'Billing'],
    ),
  ];

  // Android Projects - First batch
  static final List<Project> androidProjects = [
    Project(
      id: 'android_all_projects',
      title: 'All Android Projects Ideas',
      description: 'Comprehensive collection of Android development concepts',
      category: 'android',
      type: 'android',
      technologies: ['Android SDK', 'Java', 'Kotlin', 'Various APIs'],
    ),
    Project(
      id: 'expense_tracker_android',
      title: 'Android Group Expense Tracker Application',
      description: 'Collaborative expense tracking for groups',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'Android SDK', 'SQLite', 'Material Design'],
    ),
    Project(
      id: 'health_consulting_android',
      title: 'Smart Health Consulting Android System',
      description: 'AI-powered health consultation mobile app',
      category: 'ai',
      type: 'android',
      technologies: ['Kotlin', 'TensorFlow Lite', 'Firebase', 'ML Kit'],
    ),
    Project(
      id: 'sentence_framer_android',
      title: 'Android Sentence Framer Application',
      description: 'Language learning and sentence construction app',
      category: 'ai',
      type: 'android',
      technologies: ['Java', 'NLP', 'SQLite', 'Material Design'],
    ),
    Project(
      id: 'expense_tracker_simple',
      title: 'Android Expense Tracker',
      description: 'Personal finance management application',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'Room Database', 'MVVM', 'Charts'],
    ),
    Project(
      id: 'pattern_locking',
      title: 'Android Multi Layer Pattern Locking Project',
      description: 'Advanced security pattern lock system',
      category: 'security',
      type: 'android',
      technologies: ['Java', 'Biometric API', 'Encryption', 'Security'],
    ),
    Project(
      id: 'ai_diet_consultant',
      title: 'Android AI Diet Consultant',
      description: 'Personalized nutrition recommendations using AI',
      category: 'ai',
      type: 'android',
      technologies: ['Kotlin', 'TensorFlow Lite', 'Room', 'Retrofit'],
    ),
    Project(
      id: 'payroll_gps',
      title: 'Automated Payroll With GPS Tracking And Image Capture',
      description: 'Employee attendance with location and photo verification',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'GPS', 'Camera API', 'Firebase'],
    ),
    Project(
      id: 'universal_ticketing',
      title: 'Android Based Universal Ticketing Project',
      description: 'Multi-platform ticket booking and management system',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'QR Code', 'Payment Gateway', 'SQLite'],
    ),
    Project(
      id: 'places_finder',
      title: 'Android Places Finder Project',
      description: 'Location-based service discovery application',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'Google Maps API', 'Places API', 'GPS'],
    ),
    Project(
      id: 'electricity_bill_payment',
      title: 'Android Electricity Bill Payment Project',
      description: 'Utility bill payment and management system',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'Payment Gateway', 'QR Scanner', 'Notifications'],
    ),
    Project(
      id: 'tour_travel_agency',
      title: 'Android Tour & Travel Agency Project',
      description: 'Travel booking and itinerary management app',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'Google Maps', 'Booking APIs', 'Payment Gateway'],
    ),
    Project(
      id: 'law_system',
      title: 'Android Law System Project',
      description: 'Legal case management and documentation system',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'Document Management', 'Search', 'Security'],
    ),
    Project(
      id: 'photo_viewer',
      title: 'Photo Viewer Android Project',
      description: 'Advanced image viewing and editing application',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'Image Processing', 'Gallery API', 'Filters'],
    ),
    Project(
      id: 'file_finder_sorting',
      title: 'Android File finder and Sorting',
      description: 'File management and organization utility',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'File System API', 'Search', 'Storage'],
    ),
    Project(
      id: 'inventory_tracker',
      title: 'Android Inventory Tracker',
      description: 'Business inventory management and tracking',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'Barcode Scanner', 'Database', 'Reporting'],
    ),
    Project(
      id: 'voting_face_recognition',
      title: 'Android Voting System Using Face Recognition',
      description: 'Secure voting system with facial authentication',
      category: 'security',
      type: 'android',
      technologies: ['Kotlin', 'Face Detection', 'Encryption', 'Firebase'],
    ),
    Project(
      id: 'tts_ocr_converter',
      title: 'Android TTS OCR Converter System for People with Visual Disability',
      description: 'Accessibility app for visually impaired users',
      category: 'ai',
      type: 'android',
      technologies: ['Java', 'OCR', 'Text-to-Speech', 'Camera API'],
    ),
    Project(
      id: 'grocery_management',
      title: 'Android Grocery Management App',
      description: 'Smart grocery shopping and inventory management',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'Barcode Scanner', 'Room Database', 'MVVM'],
    ),
    Project(
      id: 'local_geofence',
      title: 'Android Local Geofence System',
      description: 'Location-based notifications and automation',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'Geofencing API', 'Background Services', 'GPS'],
    ),
    Project(
      id: 'electronic_appliance_comparison',
      title: 'Android Based Electronic Appliance Comparison Project',
      description: 'Product comparison and shopping assistant',
      category: 'android',
      type: 'android',
      technologies: ['Kotlin', 'Product APIs', 'Price Comparison', 'Reviews'],
    ),
    Project(
      id: 'crm_app',
      title: 'Android Customer Relationship Management App',
      description: 'Mobile CRM for sales and customer management',
      category: 'android',
      type: 'android',
      technologies: ['Java', 'CRM APIs', 'Contact Management', 'Analytics'],
    ),
    Project(
      id: 'geo_trends_classification',
      title: 'Geo Trends Classification Over Maps Android',
      description: 'Location-based trend analysis and visualization',
      category: 'data_science',
      type: 'android',
      technologies: ['Kotlin', 'Google Maps', 'Data Analytics', 'Machine Learning'],
    ),
    Project(
      id: 'graphical_information_system',
      title: 'Android Graphical Information System',
      description: 'Data visualization and reporting platform',
      category: 'data_science',
      type: 'android',
      technologies: ['Java', 'Charts', 'Data Visualization', 'Reports'],
    ),
  ];

  // iOS Projects - First batch
  static final List<Project> iosProjects = [
    Project(
      id: 'ios_all_projects',
      title: 'All iOS Projects List',
      description: 'Comprehensive collection of iOS development projects',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'iOS SDK', 'Xcode', 'Various Frameworks'],
    ),
    Project(
      id: 'safe_folder_ios',
      title: 'Safe Folder App',
      description: 'Secure file storage with encryption',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'Keychain', 'Encryption'],
    ),
    Project(
      id: 'amber_alert_ios',
      title: 'Amber Alert System',
      description: 'Emergency child safety alert system',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Core Location', 'Push Notifications', 'MapKit'],
    ),
    Project(
      id: 'read_me_book_ios',
      title: 'Read Me My Book App',
      description: 'Text-to-speech book reading application',
      category: 'ai',
      type: 'ios',
      technologies: ['Swift', 'AVSpeechSynthesizer', 'Core Data', 'UIKit'],
    ),
    Project(
      id: 'mobile_wallet_ios',
      title: 'Mobile Wallet and QR Code Payment System',
      description: 'Digital payment and wallet management',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'QR Scanner', 'Security Framework'],
    ),
    Project(
      id: 'daily_checklist_ios',
      title: 'Daily Checklist and Daily Routine App',
      description: 'Productivity and habit tracking application',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'UserNotifications', 'WidgetKit'],
    ),
    Project(
      id: 'health_tracker_ios',
      title: 'Personal Health Tracker iOS Application',
      description: 'Comprehensive health monitoring and tracking app',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'HealthKit', 'Core Data', 'Charts'],
    ),
    Project(
      id: 'task_alerting_ios',
      title: 'iOS Task Alerting Application',
      description: 'Smart task management with intelligent reminders',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'UserNotifications', 'Core Data', 'Siri Shortcuts'],
    ),
    Project(
      id: 'expense_tracker_ios',
      title: 'Daily Expense Tracker iOS Application',
      description: 'Personal finance management with analytics',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'Charts', 'CloudKit'],
    ),
    Project(
      id: 'doctor_appointment_ios',
      title: 'Doctor Appointment Manager iOS App',
      description: 'Healthcare appointment scheduling and management',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'Calendar Integration', 'Push Notifications'],
    ),
    Project(
      id: 'periodic_bell_ios',
      title: 'iOS Periodic Bell & Timetable Reminder Application',
      description: 'Educational scheduling and reminder system',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'UserNotifications', 'Core Data', 'Background Tasks'],
    ),
    Project(
      id: 'personal_book_ios',
      title: 'Personal Book iOS Application',
      description: 'Digital library and reading progress tracker',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'PDF Kit', 'iCloud Sync'],
    ),
    Project(
      id: 'secure_notes_ios',
      title: 'Secure Notes Storage Using Encryption iOS App',
      description: 'Encrypted note-taking with biometric security',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Keychain', 'Encryption', 'Touch ID/Face ID'],
    ),
    Project(
      id: 'wake_me_up_ios',
      title: 'Wake Me Up iOS Application',
      description: 'Smart alarm with sleep cycle optimization',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Motion', 'UserNotifications', 'HealthKit'],
    ),
    Project(
      id: 'children_safety_ios',
      title: 'Children Safety Tracking iOS Application',
      description: 'Family safety and location monitoring app',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Core Location', 'MapKit', 'Push Notifications'],
    ),
    Project(
      id: 'daily_news_ios',
      title: 'Daily News Updates iOS Application',
      description: 'Personalized news aggregation and reading app',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'News API', 'Core Data', 'Natural Language'],
    ),
    Project(
      id: 'delivery_van_tracking_ios',
      title: 'Delivery Van Tracking Over Internet using iOS',
      description: 'Real-time delivery tracking and management',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Location', 'MapKit', 'Real-time Updates'],
    ),
    Project(
      id: 'graphical_password_ios',
      title: 'Secure Authentication Using Graphical Password iOS',
      description: 'Visual password authentication system',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Touch Recognition', 'Security', 'Biometrics'],
    ),
    Project(
      id: 'smart_attendance_ios',
      title: 'Smart Attendance System iOS',
      description: 'Automated attendance tracking with smart features',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Location', 'Face Recognition', 'Core Data'],
    ),
    Project(
      id: 'vote_casting_ios',
      title: 'iOS Based Vote Casting App System',
      description: 'Secure digital voting platform for iOS',
      category: 'security',
      type: 'ios',
      technologies: ['Swift', 'Encryption', 'Biometric Auth', 'Blockchain'],
    ),
    Project(
      id: 'furniture_store_ios',
      title: 'iOS Furniture Store Project',
      description: 'E-commerce app for furniture shopping',
      category: 'ios',
      type: 'ios',
      technologies: ['Swift', 'Core Data', 'AR Kit', 'Payment Gateway'],
    ),
    Project(
      id: 'diet_monitoring_ios',
      title: 'Smart Diet Monitoring iOS Application',
      description: 'AI-powered nutrition tracking and recommendations',
      category: 'ai',
      type: 'ios',
      technologies: ['Swift', 'Core ML', 'HealthKit', 'Computer Vision'],
    ),
  ];

  static List<Project> getAllProjects() {
    return [...webProjects, ...androidProjects, ...iosProjects];
  }

  static List<Project> getProjectsByType(String type) {
    switch (type) {
      case 'web':
        return webProjects;
      case 'android':
        return androidProjects;
      case 'ios':
        return iosProjects;
      default:
        return getAllProjects();
    }
  }

  static List<Project> getProjectsByCategory(String categoryId, String type) {
    final projects = getProjectsByType(type);
    return projects.where((project) => project.category == categoryId).toList();
  }
}
